### ISSUE TITLE
Account does not exist on chain error

### ISSUE THREAD

**Issue by Lefey** [MELLIFERA-Labs/kyve-restake#5]
Hi, got error `Account '${address}' does not exist on chain. Send some tokens there before trying to query sequence.)`
but wallet exist on chain and have enoght tokens, what can be wrong?
````
{"level":30,"time":1700736353364,"pid":1,"hostname":"0801f33a4341","name":"CLI","msg":"Restake worker starting..."}
{"level":30,"time":1700736354494,"pid":1,"hostname":"0801f33a4341","name":"restake-worker","msg":"Kyve SDK initialized with grantee: kyve1vkad7wj8kh6snrwr25pldv87t37dc7kn7gku3x "}
{"level":30,"time":1700736354494,"pid":1,"hostname":"0801f33a4341","name":"restake-worker","msg":"cosmos api initialized"}
{"level":30,"time":1700736354527,"pid":1,"hostname":"0801f33a4341","name":"restake-worker","msg":"resake script started"}
/usr/src/app/app/node_modules/@cosmjs/stargate/build/stargateclient.js:135
            throw new Error(Account '${address}' does not exist on chain. Send some tokens there before trying to query sequence.);
                  ^

Error: Account 'kyve1vkad7wj8kh6snrwr25pldv87t37dc7kn7gku3x' does not exist on chain. Send some tokens there before trying to query sequence.
    at SigningStargateClient.getSequence (/usr/src/app/app/node_modules/@cosmjs/stargate/build/stargateclient.js:135:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SigningStargateClient.simulate (/usr/src/app/app/node_modules/@cosmjs/stargate/build/signingstargateclient.js:96:30)
    at async SigningStargateClient.signAndBroadcast (/usr/src/app/app/node_modules/@cosmjs/stargate/build/signingstargateclient.js:168:35)
    at async CJ.restakeHandler (/usr/src/app/app/restake-worker/index.js:41:20)

**Comment by RuslanGlaznyov** [comment]
Thanks for reporting! 
Try to use the latest release: 
https://github.com/MELLIFERA-Labs/kyve-restake/releases/tag/v1.2.0

That might be a fixed issue. Let me know if not. 
Until will leave this issue open

**Comment by Lefey** [comment]
Hi, thanks for reply, i try new version, but still the same error as before (try docker hub image and build from sources).

**Comment by RuslanGlaznyov** [comment]
@Lefey Try to use only `KYVE_ENV='kyve-1 '`  configuration for your env

**Comment by Lefey** [comment]
This helps, it was my wrong - i have devnet RPC and REST env's 😅
Thank you for help.
